name: Deploy to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Determine build type and set variables
        id: build-type
        run: |
          if [[ ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }} == true ]]; then
            echo "BUILD_TYPE=production" >> $GITHUB_OUTPUT
            echo "BASE_URL=/" >> $GITHUB_OUTPUT
          else
            echo "BUILD_TYPE=staging" >> $GITHUB_OUTPUT
            echo "BASE_URL=/${{ github.event.repository.name }}/pr-preview-${{ github.event.number }}/" >> $GITHUB_OUTPUT
          fi

      - name: Modify docusaurus.config.js
        run: |
          sed -i 's|baseUrl: '\''\/|baseUrl: '\''${{ steps.build-type.outputs.BASE_URL }}|' docusaurus.config.js
                    
          if [[ "${{ steps.build-type.outputs.BUILD_TYPE }}" == "staging" ]]; then
          sed -i '/themeConfig:/,/^    }),/ {
            /^    }),/i\
          announcementBar: {\
            id: '\''staging-environment'\'',\
            content:\
              '\''⚠️ This is a <strong>Staging Environment</strong>. Changes may not be final. For the latest production version, please visit <a href="https://iliasmavridis.github.io/test/" style="text-decoration: underline; color: inherit;">this link</a>.'\'',\
            backgroundColor: '\''#ffcc00'\'',\
            textColor: '\''#000000'\'',\
            isCloseable: false,\
          },
              }' docusaurus.config.js
          fi

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.GH_PAGES_PAT }}
          target-folder: ${{ steps.build-type.outputs.BUILD_TYPE == 'production' && '' || format('pr-preview-{0}', github.event.number) }}

      - name: Comment PR with preview URL
        if: steps.build-type.outputs.BUILD_TYPE == 'staging'
        uses: actions/github-script@v7
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview this PR at: https://${context.repo.owner}.github.io/${{ github.event.repository.name }}/pr-preview-${{ github.event.number }}/`
            })

      - name: Clean up PR preview
        if: github.event.pull_request.merged == true
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_PAT }}        
        run: |
          git push origin --delete gh-pages:pr-preview-${{ github.event.number }}