name: Docusaurus PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Determine build type
        id: build-type
        run: |
          if [[ "${{ github.event_name }}" == "push" ]] || [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "type=production" >> $GITHUB_OUTPUT
            echo "base_url=/test2/" >> $GITHUB_OUTPUT
          else
            echo "type=staging" >> $GITHUB_OUTPUT
            echo "base_url=/test2/pr-preview-${{ github.event.number }}/" >> $GITHUB_OUTPUT
          fi

      - name: Debug Build Type
        run: |
          echo "Build type: ${{ steps.build-type.outputs.type }}"
          echo "Base URL: ${{ steps.build-type.outputs.base_url }}"
          echo "Event name: ${{ github.event_name }}"
          echo "PR merged: ${{ github.event.pull_request.merged }}"

      - name: Modify docusaurus.config.js
        run: |
          sed -i 's|baseUrl: '\''\/test2\/|baseUrl: '\''${{ steps.build-type.outputs.base_url }}|' docusaurus.config.js
          
          if [[ "${{ steps.build-type.outputs.type }}" == "staging" ]]; then
            sed -i '/themeConfig:/,/^    }),/ {
              /^    }),/i\
          announcementBar: {\
          id: '\''staging-environment'\'',\
          content:\
            '\''⚠️ This is a <strong>Staging Environment</strong> for PR #${{ github.event.number }}. Changes may not be final.'\'',\
          backgroundColor: '\''#ffcc00'\'',\
          textColor: '\''#000000'\'',\
          isCloseable: false,\
          },
            }' docusaurus.config.js
          else
            sed -i '/announcementBar:/,/},/d' docusaurus.config.js
          fi

      - name: Build website
        run: npm run build

      - name: Debug Build Output
        run: |
          echo "Contents of build directory:"
          ls -R build

      - name: Deploy Production to GitHub Pages
        if: steps.build-type.outputs.type == 'production'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git clone --single-branch --branch gh-pages "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
          cd gh-pages
          # Overwrite existing files with new build
          cp -rf ../build/* .
          git add .
          git commit -m "Update production Docusaurus site" || echo "No changes to commit"
          git push

      - name: Deploy PR Preview
        if: steps.build-type.outputs.type == 'staging'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: pr-preview-${{ github.event.number }}
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Comment PR with preview URL
        if: steps.build-type.outputs.type == 'staging'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          gh pr comment $PR_NUMBER --body "Preview this PR at: https://$REPO_OWNER.github.io/$REPO_NAME/pr-preview-$PR_NUMBER/"

      - name: Cleanup PR preview
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_PAT }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          if [ -d "gh-pages" ]; then
            cd gh-pages
            git pull origin gh-pages
          else
            git clone --single-branch --branch gh-pages https://${{ secrets.GH_PAGES_PAT }}@github.com/${{ github.repository }}.git gh-pages
            cd gh-pages
          fi
          
          if [ -d "pr-preview-$PR_NUMBER" ]; then
            rm -rf "pr-preview-$PR_NUMBER"
            git commit -m "Remove PR preview for #$PR_NUMBER"
            git push
          else
            echo "Preview folder for PR #$PR_NUMBER not found. Skipping cleanup."
          fi

      - name: Debug Deployment
        run: |
          echo "Deployment completed"
          echo "Build type: ${{ steps.build-type.outputs.type }}"
          echo "Target folder: ${{ steps.build-type.outputs.type == 'production' && 'root' || format('pr-preview-{0}', github.event.number) }}"